import os
import pandas as pd
from typing import Dict, Any, List
from langchain_core.messages import SystemMessage, HumanMessage

from agent.state import AgentState
from agent.llm import get_llm
from agent.parser import CSVParser

def clean_code(code_str: str) -> str:
    """Strip markdown code blocks from the generated string."""
    code_str = code_str.strip()
    if code_str.startswith("```python"):
        code_str = code_str[len("```python"):].strip()
    elif code_str.startswith("```"):
        code_str = code_str[len("```"):].strip()
    if code_str.endswith("```"):
        code_str = code_str[:-3].strip()
    return code_str.strip()

def parse_csv_node(state: AgentState) -> Dict[str, Any]:
    """
    Node to parse CSV and construct a metadata/schema summary.
    """
    csv_path = state.get("csv_path")
    if not csv_path or not os.path.exists(csv_path):
        return {"error": f"CSV file path '{csv_path}' does not exist."}
    
    try:
        df = CSVParser.load_csv(csv_path)
        summary = CSVParser.get_summary(df)
        formatted_summary = CSVParser.format_summary_for_llm(summary)
        return {
            "csv_summary": formatted_summary,
            "error": None
        }
    except Exception as e:
        return {"error": f"Failed to parse CSV: {str(e)}"}

def understand_query_node(state: AgentState) -> Dict[str, Any]:
    """
    Node to analyze the query and generate a pandas expression to extract data.
    """
    llm = get_llm()
    query = state.get("query")
    summary = state.get("csv_summary")
    feedback = state.get("feedback")
    error = state.get("error")
    
    system_prompt = (
        "You are an expert data analyst assistant. Your task is to write a single-line Python expression using Pandas "
        "to filter or aggregate the DataFrame 'df' to extract the data needed to answer the user's query.\n\n"
        "Rules:\n"
        "1. Output ONLY the raw Python expression that can be evaluated using eval(expression, globals, locals).\n"
        "2. Do not include markdown formatting, backticks, comments, imports, or explanation.\n"
        "3. Ensure the expression is safe and only queries/inspects the DataFrame 'df'.\n"
        "4. Standard functions available: len, sum, max, min, str, int, float, list, dict, set.\n\n"
        "Examples:\n"
        "- Query: 'What is the average salary of employees?' -> df['salary'].mean()\n"
        "- Query: 'List all employees in the IT department' -> df[df['department'] == 'IT']\n"
        "- Query: 'How many rows are in the dataset?' -> len(df)\n"
    )
    
    user_prompt = f"CSV Schema and Structure:\n{summary}\n\nUser Query: {query}\n"
    if error:
        user_prompt += f"\nPrevious attempt failed with error: {error}. Please write a corrected, valid Pandas expression."
    if feedback:
        user_prompt += f"\nHuman validator gave this feedback on the previous response: {feedback}. Adjust the Pandas expression to query the correct data."
        
    messages = [
        SystemMessage(content=system_prompt),
        HumanMessage(content=user_prompt)
    ]
    
    try:
        response = llm.invoke(messages)
        pandas_query = clean_code(response.content)
        return {
            "pandas_query": pandas_query,
            "error": None,
            "feedback": None
        }
    except Exception as e:
        return {"error": f"LLM error: {str(e)}"}

def extract_data_node(state: AgentState) -> Dict[str, Any]:
    """
    Node to execute the generated pandas query safely.
    """
    csv_path = state.get("csv_path")
    pandas_query = state.get("pandas_query")
    
    if not pandas_query:
        return {"error": "No query generated by LLM."}
    
    try:
        df = CSVParser.load_csv(csv_path)
        
        # Build a safe environment for eval
        eval_globals = {
            "__builtins__": {
                "len": len,
                "sum": sum,
                "max": max,
                "min": min,
                "str": str,
                "int": int,
                "float": float,
                "list": list,
                "dict": dict,
                "set": set,
            }
        }
        eval_locals = {"df": df, "pd": pd}
        
        result = eval(pandas_query, eval_globals, eval_locals)
        
        # Formulate string output based on type of result
        if isinstance(result, pd.DataFrame):
            extracted_str = result.to_string(index=False)
        elif isinstance(result, pd.Series):
            extracted_str = result.to_string()
        else:
            extracted_str = str(result)
            
        return {
            "extracted_data": extracted_str,
            "error": None
        }
    except Exception as e:
        return {"error": f"{type(e).__name__}: {str(e)}"}

def draft_response_node(state: AgentState) -> Dict[str, Any]:
    """
    Node to draft the final response to the user query using the extracted data.
    """
    llm = get_llm()
    query = state.get("query")
    extracted_data = state.get("extracted_data")
    
    system_prompt = (
        "You are an expert data analyst assistant. Answer the user's query using only the provided extracted data.\n"
        "Guidelines:\n"
        "1. Keep the answer clear, professional, and concise.\n"
        "2. Do not make assumptions beyond the extracted data.\n"
        "3. If the data is empty or insufficient, state that clearly.\n"
        "4. Format numerical outputs (averages, sums) nicely."
    )
    
    user_prompt = f"User Query: {query}\n\nExtracted Data from CSV:\n{extracted_data}\n\nAnswer:"
    
    messages = [
        SystemMessage(content=system_prompt),
        HumanMessage(content=user_prompt)
    ]
    
    try:
        response = llm.invoke(messages)
        return {
            "response": response.content.strip(),
            "error": None
        }
    except Exception as e:
        return {"error": f"Failed to draft response: {str(e)}"}

def human_validation_node(state: AgentState) -> Dict[str, Any]:
    """
    Placeholder node for Human-in-the-Loop validation.
    This node serves as the synchronization point.
    """
    return {}
